export function renderModals() {
  return `
    <div id="moodHistoryModal" class="modal-overlay"><div class="modal-content p-5"><div class="flex justify-between items-center border-b border-dopamine-yellow/30 pb-2 mb-3"><h3 class="text-lg font-bold text-dopamine-orange"><i class="far fa-smile"></i> 圣意起居注</h3><button class="close-modal-btn text-gray-400 hover:text-dopamine-pink text-xl">&times;</button></div><div id="moodHistoryList" class="space-y-2 max-h-[50vh] overflow-y-auto pr-1">加载中...</div></div></div>
    <div id="taskHistoryModal" class="modal-overlay"><div class="modal-content p-5"><div class="flex justify-between items-center border-b border-dopamine-yellow/30 pb-2 mb-3"><h3 class="text-lg font-bold text-dopamine-pink"><i class="fas fa-check-circle"></i> 已批奏折 · 归档</h3><button class="close-modal-btn text-gray-400 hover:text-dopamine-pink text-xl">&times;</button></div><div id="taskHistoryList" class="space-y-2 max-h-[50vh] overflow-y-auto pr-1">加载中...</div></div></div>
    <div id="ideaHistoryModal" class="modal-overlay"><div class="modal-content p-5"><div class="flex justify-between items-center border-b border-dopamine-yellow/30 pb-2 mb-3"><h3 class="text-lg font-bold text-dopamine-mint"><i class="fas fa-lightbulb"></i> 天恩闪念 · 历史</h3><button class="close-modal-btn text-gray-400 hover:text-dopamine-pink text-xl">&times;</button></div><div id="ideaHistoryList" class="space-y-2 max-h-[50vh] overflow-y-auto pr-1">加载中...</div></div></div>
    <div id="habitHistoryModal" class="modal-overlay"><div class="modal-content p-5"><div class="flex justify-between items-center border-b border-dopamine-sky/30 pb-2 mb-3"><h3 class="text-lg font-bold text-dopamine-sky"><i class="fas fa-book-open"></i> 圣躬日课 · 归档</h3><button class="close-modal-btn text-gray-400 hover:text-dopamine-pink text-xl">&times;</button></div><div id="habitHistoryList" class="space-y-2 max-h-[50vh] overflow-y-auto pr-1">加载中...</div></div></div>

    <div id="dayDetailModal" class="modal-overlay"><div class="modal-content p-5"><div class="flex justify-between items-center border-b border-dopamine-sky/30 pb-2 mb-3"><h3 class="text-lg font-bold text-dopamine-sky flex items-center gap-2"><i class="far fa-calendar-check"></i> <span id="dayDetailTitle">日期详情</span></h3><button class="close-modal-btn text-gray-400 hover:text-dopamine-pink text-xl">&times;</button></div><div class="space-y-4"><div class="bg-gradient-to-r from-orange-50 to-amber-50 rounded-xl p-3 flex justify-between items-center shadow-sm"><span class="text-sm font-bold text-dopamine-orange"><i class="fas fa-hourglass-half"></i> 专注时长</span><span id="detailFocusTime" class="font-black text-2xl text-dopamine-orange">0 min</span></div><div><h4 class="text-xs font-bold text-gray-500 mb-2 flex items-center gap-1"><i class="fas fa-check-circle text-dopamine-mint"></i> 这一天完成的任务</h4><div id="detailCompletedTasks" class="space-y-2 max-h-32 overflow-y-auto text-sm pr-1"></div></div><div><h4 class="text-xs font-bold text-gray-500 mb-2 flex items-center gap-1"><i class="fas fa-tasks text-dopamine-sky"></i> 当前的待办与压力</h4><div id="detailPendingTasks" class="space-y-2 max-h-32 overflow-y-auto text-sm pr-1"></div></div><div><h4 class="text-xs font-bold text-gray-500 mb-2 flex items-center gap-1"><i class="fas fa-seedling text-dopamine-mint"></i> 圣躬归档</h4><div id="detailHabitRecords" class="space-y-2 max-h-40 overflow-y-auto text-sm pr-1"></div></div></div></div></div>

    <div id="habitModal" class="modal-overlay">
      <div class="modal-content p-5">
        <div class="flex justify-between items-center border-b border-dopamine-mint/30 pb-2 mb-3">
          <h3 class="text-lg font-bold text-dopamine-mint flex items-center gap-2"><i class="fas fa-seedling"></i> <span id="habitModalTitle">新增打卡习惯</span></h3>
          <button class="close-modal-btn text-gray-400 hover:text-dopamine-pink text-xl" data-action="close-habit-modal">&times;</button>
        </div>
        <input type="hidden" id="habitModalId">
        <div class="space-y-4">
          <div><label class="text-xs font-bold text-gray-500">习惯名称</label><input id="habitModalName" type="text" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-mint text-sm" placeholder="比如：喝水 / 背单词 / 拉伸"></div>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-3">
            <div><label class="text-xs font-bold text-gray-500">单位（可不填）</label><input id="habitModalUnit" type="text" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-mint text-sm" placeholder="杯 / 分钟 / 次"></div>
            <div><label class="text-xs font-bold text-gray-500">目标量（可不填）</label><input id="habitModalTarget" type="number" min="0" step="1" inputmode="numeric" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-mint text-sm" placeholder="例如 8"></div>
          </div>
          <div class="text-xs text-gray-400 leading-6 bg-green-50 border border-green-100 rounded-xl p-3">不填目标量：可直接打钩，也可以填数量后再打钩。<br>填了目标量：会按当前数量显示进度条，也可以手动标记完成。</div>
          <div class="flex gap-2 pt-1">
            <button data-action="save-habit" class="flex-1 bg-dopamine-mint text-white py-2.5 rounded-xl font-bold shadow-sm hover:opacity-90 transition">💾 保存习惯</button>
            <button data-action="delete-habit" id="habitModalDeleteBtn" class="bg-red-100 text-red-500 px-4 py-2.5 rounded-xl font-bold shadow-sm hover:bg-red-200 transition hidden">删除</button>
          </div>
        </div>
      </div>
    </div>

    <div id="habitRecordModal" class="modal-overlay">
      <div class="modal-content p-5">
        <div class="flex justify-between items-center border-b border-dopamine-sky/30 pb-2 mb-3">
          <h3 class="text-lg font-bold text-dopamine-sky flex items-center gap-2"><i class="fas fa-pen-to-square"></i> 编辑今日打卡</h3>
          <button class="close-modal-btn text-gray-400 hover:text-dopamine-pink text-xl" data-action="close-habit-record-modal">&times;</button>
        </div>
        <input type="hidden" id="habitRecordModalId">
        <div class="space-y-4">
          <div class="bg-sky-50 border border-sky-100 rounded-xl p-3"><div class="text-xs text-gray-400">打卡项</div><div id="habitRecordModalName" class="font-bold text-gray-800 mt-1">-</div></div>
          <div><label class="text-xs font-bold text-gray-500">当前数量</label><div class="flex items-center gap-2 mt-1"><input id="habitRecordModalValue" type="number" min="0" step="1" inputmode="numeric" class="w-full p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-sky text-sm"><span id="habitRecordModalUnit" class="text-sm text-gray-500 min-w-[48px]"></span></div></div>
          <label class="flex items-center gap-2 text-sm text-gray-700 bg-gray-50 rounded-xl px-3 py-3 border border-gray-100"><input id="habitRecordModalChecked" type="checkbox" class="w-4 h-4">今日议定</label>
          <div class="flex gap-2 pt-1"><button data-action="save-habit-record" class="flex-1 bg-dopamine-sky text-white py-2.5 rounded-xl font-bold shadow-sm hover:opacity-90 transition">✅ 保存记录</button></div>
        </div>
      </div>
    </div>

    <div id="checkInModal" class="modal-overlay"><div class="modal-content p-5"><div class="flex justify-between items-center border-b border-dopamine-yellow/30 pb-2 mb-3"><h3 class="text-lg font-bold text-gray-800" id="checkModalTitle">📝 时段补录与复盘</h3><button class="close-modal-btn text-gray-400 hover:text-dopamine-pink text-xl">&times;</button></div><input type="hidden" id="checkModalPeriod"><div class="space-y-4"><div class="flex gap-4"><div class="flex-1"><label class="text-xs font-bold text-gray-500">上朝时间 (可修改)</label><input type="time" id="checkModalStart" class="w-full mt-1 p-2 border rounded-lg bg-gray-50 outline-none focus:border-dopamine-orange text-sm"></div><div class="flex-1"><label class="text-xs font-bold text-gray-500">退朝时间 (可修改)</label><input type="time" id="checkModalEnd" class="w-full mt-1 p-2 border rounded-lg bg-gray-50 outline-none focus:border-dopamine-orange text-sm"></div></div><div><label class="text-xs font-bold text-gray-500">本朝精力评估 (任选其一)</label><div class="flex gap-2 mt-1"><button type="button" class="energy-btn flex-1 py-1.5 border border-gray-200 rounded-lg text-xs font-bold text-gray-600 bg-gray-50 transition" data-energy="🔥 龙威浩荡">🔥 龙威</button><button type="button" class="energy-btn flex-1 py-1.5 border border-gray-200 rounded-lg text-xs font-bold text-gray-600 bg-gray-50 transition" data-energy="😫 圣体违和">😫 违和</button><button type="button" class="energy-btn flex-1 py-1.5 border border-gray-200 rounded-lg text-xs font-bold text-gray-600 bg-gray-50 transition" data-energy="👥 朝堂纷争">👥 杂政</button></div><input type="hidden" id="checkModalEnergy"></div><div><label class="text-xs font-bold text-gray-500">圣裁碎碎念 / 奏折产出</label><textarea id="checkModalNote" rows="2" class="w-full mt-1 p-2 border rounded-lg bg-gray-50 outline-none focus:border-dopamine-orange resize-none text-sm" placeholder="比如：跑通了模型，或者导师（太上皇）临时加了活儿..."></textarea></div><button data-action="save-check-modal" class="w-full bg-dopamine-orange text-white py-2.5 rounded-xl font-bold shadow-sm hover:bg-orange-500 transition">💾 载入史册</button></div></div></div>

    <div id="pendingSettlementModal" class="modal-overlay"><div class="modal-content p-5"><div class="flex justify-between items-center border-b border-dopamine-yellow/30 pb-2 mb-3"><h3 class="text-lg font-bold text-dopamine-orange flex items-center gap-2"><i class="fas fa-scroll"></i> 上一段自由理政待结算</h3><button id="pendingSettlementCloseBtn" class="text-gray-400 hover:text-dopamine-pink text-xl">&times;</button></div><div class="space-y-4"><div class="bg-gradient-to-r from-orange-50 to-amber-50 rounded-xl p-3 text-sm text-gray-700 leading-6 border border-orange-100"><p>检测到上一段 <span class="font-bold text-dopamine-orange">自由理政</span> 已超过 <span class="font-bold">8 小时</span> 未活动。</p><p class="mt-1">请补录这次实际理政时长，或放弃记录。</p></div><div class="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm"><div class="bg-gray-50 rounded-xl p-3 border border-gray-100"><div class="text-xs text-gray-400 mb-1">开始时间</div><div id="pendingSettlementStartText" class="font-semibold text-gray-700">-</div></div><div class="bg-gray-50 rounded-xl p-3 border border-gray-100"><div class="text-xs text-gray-400 mb-1">最后活动时间</div><div id="pendingSettlementLastActivityText" class="font-semibold text-gray-700">-</div></div></div><div class="bg-green-50 rounded-xl p-3 border border-green-100"><label class="text-xs font-bold text-green-700">建议补录时长（分钟）</label><div id="pendingSettlementSuggestedText" class="text-lg font-black text-dopamine-mint mt-1">0 分钟</div></div><div><label class="text-xs font-bold text-gray-500">实际理政时长（分钟）</label><input id="pendingSettlementMinutesInput" type="number" min="0" step="1" class="w-full mt-1 p-2.5 border rounded-lg bg-gray-50 outline-none focus:border-dopamine-orange text-sm" placeholder="请输入分钟数"><div class="text-[11px] text-gray-400 mt-1">输入 0 表示明确放弃记录；点“稍后再说”则下次继续提醒。</div></div><div class="flex flex-col sm:flex-row gap-2 pt-1"><button id="confirmPendingSettlementBtn" class="flex-1 bg-dopamine-orange text-white py-2.5 rounded-xl font-bold shadow-sm hover:bg-orange-500 transition">💾 补录并保存</button><button id="discardPendingSettlementBtn" class="flex-1 bg-gray-100 text-gray-700 py-2.5 rounded-xl font-bold shadow-sm hover:bg-gray-200 transition">🗑️ 放弃这次记录</button><button id="postponePendingSettlementBtn" class="flex-1 bg-dopamine-sky text-white py-2.5 rounded-xl font-bold shadow-sm hover:opacity-90 transition">⏳ 稍后再说</button></div></div></div></div>


    <div id="ingredientModal" class="modal-overlay">
      <div class="modal-content p-5">
        <div class="flex justify-between items-center border-b border-green-200/60 pb-2 mb-3">
          <h3 id="ingredientModalTitle" class="text-lg font-bold text-dopamine-mint flex items-center gap-2"><i class="fas fa-book"></i> 新增饮子</h3>
          <button class="close-modal-btn text-gray-400 hover:text-dopamine-pink text-xl" data-action="close-ingredient-modal">&times;</button>
        </div>
        <input type="hidden" id="ingredientModalId">
        <div class="space-y-4">
          <div><label class="text-xs font-bold text-gray-500">名称</label><input id="ingredientModalName" type="text" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-mint text-sm" placeholder="如：耶加雪菲 / 铁观音"></div>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-3"><div><label class="text-xs font-bold text-gray-500">大类</label><select id="ingredientModalType" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-mint text-sm"><option value="tea">茶</option><option value="coffee">咖啡</option><option value="herbal">花草</option><option value="other">其他</option></select></div><div><label class="text-xs font-bold text-gray-500">类别</label><input id="ingredientModalCategory" type="text" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-mint text-sm" placeholder="如：乌龙 / SOE / 红茶"></div></div>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-3"><div><label class="text-xs font-bold text-gray-500">品牌 / 来源</label><input id="ingredientModalBrand" type="text" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-mint text-sm"></div><div><label class="text-xs font-bold text-gray-500">产地</label><input id="ingredientModalOrigin" type="text" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-mint text-sm"></div></div>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-3"><div><label class="text-xs font-bold text-gray-500">工艺 / 处理</label><input id="ingredientModalProcess" type="text" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-mint text-sm" placeholder="如：水洗 / 焙火 / 发酵"></div><div><label class="text-xs font-bold text-gray-500">火候 / 烘焙</label><input id="ingredientModalRoastLevel" type="text" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-mint text-sm" placeholder="如：浅烘 / 轻焙"></div></div>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-3"><div><label class="text-xs font-bold text-gray-500">状态</label><input id="ingredientModalStatus" type="text" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-mint text-sm" placeholder="如：在饮 / 回购候选"></div><div><label class="text-xs font-bold text-gray-500">风味</label><input id="ingredientModalFlavor" type="text" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-mint text-sm"></div></div>
          <div><label class="text-xs font-bold text-gray-500">备注</label><textarea id="ingredientModalNote" rows="3" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-mint resize-none text-sm"></textarea></div>
          <div class="flex gap-2 pt-1"><button data-action="save-ingredient" class="flex-1 bg-dopamine-mint text-white py-2.5 rounded-xl font-bold shadow-sm hover:opacity-90 transition">💾 保存饮子</button><button data-action="delete-ingredient" id="ingredientModalDeleteBtn" class="bg-red-100 text-red-500 px-4 py-2.5 rounded-xl font-bold shadow-sm hover:bg-red-200 transition hidden">删除</button></div>
        </div>
      </div>
    </div>

    <div id="foodRecordModal" class="modal-overlay">
      <div class="modal-content p-5">
        <div class="flex justify-between items-center border-b border-amber-200/60 pb-2 mb-3">
          <h3 id="foodRecordModalTitle" class="text-lg font-bold text-dopamine-orange flex items-center gap-2"><i class="fas fa-bowl-food"></i> 新增今日饮馔</h3>
          <button class="close-modal-btn text-gray-400 hover:text-dopamine-pink text-xl" data-action="close-food-record-modal">&times;</button>
        </div>
        <input type="hidden" id="foodRecordModalId">
        <div class="space-y-4">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-3"><div><label class="text-xs font-bold text-gray-500">时间</label><input id="foodRecordModalTime" type="time" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-orange text-sm"></div><div><label class="text-xs font-bold text-gray-500">类别</label><select id="foodRecordModalCategory" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-orange text-sm"><option value="drink">饮子</option><option value="food">膳食</option><option value="supplement">补剂</option><option value="other">其他</option></select></div></div>
          <div><label class="text-xs font-bold text-gray-500">名称</label><input id="foodRecordModalName" type="text" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-orange text-sm" placeholder="如：手冲 / 乌龙茶 / 晚饭"></div>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-3"><div><label class="text-xs font-bold text-gray-500">数量</label><input id="foodRecordModalAmount" type="number" min="0" step="0.1" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-orange text-sm" placeholder="可不填"></div><div><label class="text-xs font-bold text-gray-500">单位</label><input id="foodRecordModalUnit" type="text" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-orange text-sm" placeholder="杯 / ml / 份"></div></div>
          <div><label class="text-xs font-bold text-gray-500">关联饮子</label><select id="foodRecordModalIngredientId" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-orange text-sm"></select></div>
          <div><label class="text-xs font-bold text-gray-500">备注</label><textarea id="foodRecordModalNote" rows="3" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-orange resize-none text-sm"></textarea></div>
          <div class="flex gap-2 pt-1"><button data-action="save-food-record" class="flex-1 bg-dopamine-orange text-white py-2.5 rounded-xl font-bold shadow-sm hover:bg-orange-500 transition">💾 保存记录</button><button data-action="delete-food-record-from-modal" id="foodRecordModalDeleteBtn" class="bg-red-100 text-red-500 px-4 py-2.5 rounded-xl font-bold shadow-sm hover:bg-red-200 transition hidden">删除</button></div>
        </div>
      </div>
    </div>


    <div id="taskDetailModal" class="modal-overlay">
      <button type="button" data-action="close-task-modal" class="task-modal-header-close flex-shrink-0">&times;</button>
      <div class="modal-content p-5" style="width: min(50vw, 500px); max-height: 50vh;">
        <div class="task-modal-header-pill mb-4">
          <span id="taskModalTitle" class="hidden">计划详情</span>
          <div class="relative flex-shrink-0"><select id="taskModalPriority" class="task-modal-header-priority"><option value="high">🔴紧急</option><option value="medium">🟡重要</option><option value="low">🟢日常</option></select><i class="fas fa-chevron-down pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[10px] text-amber-700/70"></i></div>
          <input id="taskModalName" type="text" class="task-modal-header-name" placeholder="输入计划名称">
          <button type="button" id="taskModalStatus" class="task-modal-header-status flex-shrink-0" data-status="待议" data-action="cycle-task-modal-status"><span class="text-[11px] leading-none">📝</span><span>待议</span></button>
        </div>
        <input type="hidden" id="taskModalId">
        <div class="space-y-4">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-3"><div><label class="text-xs font-bold text-gray-500">开始日期</label><input id="taskModalStartDate" type="date" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-orange text-sm"></div><div><label class="text-xs font-bold text-gray-500">截止日期</label><input id="taskModalDueDate" type="date" class="w-full mt-1 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-orange text-sm"></div></div>
          <div><div class="flex items-center justify-between gap-3"><label class="text-xs font-bold text-gray-500">标签</label><span class="text-[11px] text-gray-400">点一下选中 / 取消，右键删除公共标签</span></div><div id="taskModalTags" class="flex flex-wrap gap-2 mt-2"></div><div class="flex flex-col sm:flex-row gap-2 mt-3"><input id="taskTagInput" type="text" placeholder="添加新标签，回车即可" class="w-full sm:w-56 p-2.5 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-orange text-sm"><button type="button" data-action="add-tag-from-input" class="text-xs px-3 py-2 rounded-full bg-purple-50 text-dopamine-purple border border-purple-100 whitespace-nowrap font-semibold">+ 添加标签</button></div></div>
          <div><div class="flex items-center justify-between"><label class="text-xs font-bold text-gray-500">子任务</label><button type="button" data-action="add-subtask" class="text-xs px-3 py-1.5 rounded-full bg-blue-50 text-dopamine-sky border border-blue-100 whitespace-nowrap">+ 添加子任务</button></div><div id="taskModalSubtasks" class="space-y-2 mt-2"></div></div>
          <div><div class="flex items-center justify-between mb-2"><label class="text-xs font-bold text-gray-500">备注（Markdown）</label><button type="button" id="taskMarkdownToggleBtn" data-action="toggle-task-markdown-editor" class="text-xs px-3 py-1.5 rounded-full bg-orange-50 text-dopamine-orange border border-orange-100">编辑 Markdown</button></div><div id="taskMarkdownEditorWrap" class="hidden"><textarea id="taskModalNoteMarkdown" rows="8" class="w-full p-3 border rounded-xl bg-gray-50 outline-none focus:border-dopamine-orange resize-none text-sm" placeholder="- 风险点&#10;- 下一步&#10;- 需要谁配合"></textarea></div><div id="taskModalNotePreview" class="markdown-preview-prose w-full p-4 border rounded-2xl bg-white min-h-[220px] overflow-y-auto text-sm max-w-none shadow-sm"></div></div>
          <div class="flex gap-2 pt-2"><button data-action="save-task" data-close="false" class="flex-1 bg-white text-dopamine-orange py-2.5 rounded-xl font-bold shadow-sm border border-dopamine-orange/30 hover:bg-orange-50 transition">💾 保存</button><button data-action="save-task" data-close="true" class="flex-1 bg-dopamine-orange text-white py-2.5 rounded-xl font-bold shadow-sm hover:bg-orange-500 transition">✅ 保存并关闭</button><button data-action="delete-task-from-modal" id="taskModalDeleteBtn" class="bg-red-100 text-red-500 px-4 py-2.5 rounded-xl font-bold shadow-sm hover:bg-red-200 transition">删除</button></div>
        </div>
      </div>
    </div>
  `;
}
