export function renderHeader() {
  return `
    <div class="flex flex-wrap justify-between items-center gap-4 mb-6 md:mb-8">
      <div class="flex items-center gap-4">
        <div id="avatarTrigger" class="relative group cursor-pointer" title="点击更换头像">
          <img id="userAvatar" src="https://api.dicebear.com/7.x/notionists/svg?seed=PhD&backgroundColor=ffb8b8" alt="User Avatar" class="w-16 h-16 rounded-full border-4 border-white shadow-md object-cover transition-transform group-hover:scale-105 bg-white">
          <div class="absolute inset-0 bg-black/40 rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity"><i class="fas fa-camera text-white text-sm"></i></div>
          <input type="file" id="avatarInput" accept="image/*" class="hidden">
        </div>
        <div>
          <h1 class="text-3xl md:text-4xl font-extrabold tracking-tight bg-gradient-to-r from-dopamine-orange to-dopamine-pink bg-clip-text text-transparent flex items-center gap-2"><i class="fas fa-crown text-dopamine-orange"></i>争不当赵佶<span id="streakBadge" class="hidden bg-gradient-to-r from-orange-400 to-pink-500 text-white px-3 py-1 rounded-full text-sm font-bold shadow-sm ml-2 items-center gap-1"><i class="fas fa-fire"></i> 连续上朝 <span id="streakCount">0</span> 天</span></h1>
          <p class="text-amber-600/80 text-sm mt-1 flex items-center gap-2"><i class="far fa-calendar-alt text-dopamine-sky"></i><span id="currentDate"></span><span class="w-1 h-1 bg-amber-300 rounded-full"></span><span>上朝科研否？不开心就早时退朝！</span></p>
        </div>
      </div>
      <div class="flex flex-col gap-2 items-end">
        <div class="bg-white/80 backdrop-blur-sm rounded-2xl shadow-md px-3 py-2 flex items-center gap-2 border border-dopamine-yellow/40"><span class="text-sm font-bold text-dopamine-orange flex items-center gap-1"><i class="far fa-smile-wink"></i> 龙体圣意</span><div class="flex gap-2 text-2xl"><span data-mood="happy" class="mood-emoji cursor-pointer" role="button" aria-label="开心">😊</span><span data-mood="neutral" class="mood-emoji cursor-pointer" role="button" aria-label="一般">😐</span><span data-mood="sad" class="mood-emoji cursor-pointer" role="button" aria-label="不开心">😔</span></div><button id="viewMoodHistoryBtn" class="bg-gradient-to-r from-dopamine-yellow to-dopamine-orange text-white text-xs px-2.5 py-1 rounded-full shadow-sm hover:shadow transition flex items-center gap-1"><i class="fas fa-history"></i> 史册</button><div id="moodHint" class="text-xs text-dopamine-mint ml-0"></div></div>
        <div class="flex gap-2"><button data-action="toggle-layout-lock" id="layoutLockBtn" class="bg-gray-100 hover:bg-gray-200 text-gray-600 text-xs px-3 py-1.5 rounded-full border border-gray-300 transition flex items-center gap-1 shadow-sm font-medium"><i class="fas fa-lock"></i> 阵法锁定</button><button data-action="export-data" class="bg-white hover:bg-amber-50 text-dopamine-orange text-xs px-3 py-1.5 rounded-full border border-dopamine-yellow/50 transition flex items-center gap-1 shadow-sm font-medium"><i class="fas fa-download"></i> 修史</button><button id="importTrigger" class="bg-white hover:bg-green-50 text-dopamine-mint text-xs px-3 py-1.5 rounded-full border border-dopamine-mint/50 transition flex items-center gap-1 shadow-sm font-medium"><i class="fas fa-upload"></i> 光复</button><input type="file" id="importInput" accept=".json" class="hidden"></div>
      </div>
    </div>
  `;
}

export function renderDashboard() {
  return `
    <div id="dashboard-container" class="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <div id="module-focus" class="draggable-module col-span-1 lg:col-span-2 rounded-2xl shadow-colorful p-5 md:p-6" style="border-top: 4px solid #FF6B8B;">
        <div class="module-controls absolute top-3 right-3 flex gap-2 z-10"><button data-action="toggle-module-size" class="w-8 h-8 rounded-full bg-gray-100 hover:bg-dopamine-sky/20 text-gray-500 hover:text-dopamine-sky flex items-center justify-center transition" title="切换 满宽/半宽并列"><i class="fas fa-expand-arrows-alt"></i></button><div class="drag-handle w-8 h-8 rounded-full bg-gray-100 hover:bg-orange-100 text-gray-500 hover:text-dopamine-orange flex items-center justify-center transition cursor-grab" title="拖拽排序"><i class="fas fa-grip-horizontal"></i></div></div>
        <div class="flex flex-wrap items-center justify-between gap-4 mt-2"><div class="flex items-center gap-3"><div class="w-12 h-12 rounded-full bg-dopamine-yellow/20 flex items-center justify-center"><i class="fas fa-hourglass-half text-dopamine-orange text-2xl"></i></div><div><h2 class="text-xl font-bold text-gray-800">今日理政时间</h2><p class="text-gray-500 text-xs">番茄工作法 · 累积能量</p></div></div><div class="bg-dopamine-yellow/10 px-6 py-3 rounded-2xl text-center mt-4 sm:mt-0"><span id="todayFocusMinutes" class="text-4xl md:text-5xl font-black text-dopamine-orange">0</span><span class="text-xl font-semibold text-dopamine-orange/80 ml-1">分钟</span></div></div>
        <div class="mt-5 flex flex-wrap gap-4 items-center justify-between border-t border-dopamine-yellow/20 pt-4"><div class="flex gap-2 items-center w-full md:w-auto"><select id="focusMode" class="px-3 py-2.5 rounded-xl border border-dopamine-yellow/50 bg-amber-50/30 focus:border-dopamine-orange outline-none text-sm text-gray-600 font-medium transition-colors"><option value="free">♾️ 自由理政</option><option value="25">🍅 25分钟番茄钟</option><option value="50">🧠 50分钟深度钟</option></select><button id="startFocusBtn" class="bg-dopamine-orange hover:bg-dopamine-orange/85 text-white px-4 py-2.5 rounded-xl shadow-md flex items-center gap-2 transition font-medium"><i class="fas fa-play-circle"></i> 开始审阅</button><button id="stopFocusBtn" class="bg-dopamine-mint hover:bg-dopamine-mint/80 text-white px-4 py-2.5 rounded-xl shadow-md flex items-center gap-2 transition font-medium"><i class="fas fa-stop-circle"></i> 小憩片刻</button></div><div class="flex items-center gap-3"><div id="countdownDisplay" class="hidden text-2xl font-black text-dopamine-orange bg-orange-50 px-3 py-1 rounded-lg border border-orange-100">25:00</div><div id="focusStatusBadge" class="text-sm bg-dopamine-lime/10 text-dopamine-mint px-3 py-1.5 rounded-full flex items-center gap-2"><i class="fas fa-info-circle"></i> <span id="focusActiveState">⏸️ 暂无专注</span></div></div></div>
      </div>

      <div id="module-routine" class="draggable-module col-span-1 lg:col-span-2 rounded-2xl shadow-colorful p-5 md:p-6" style="border-left: 8px solid #43AA8B;">
        <div class="module-controls absolute top-3 right-3 flex gap-2 z-10"><button data-action="toggle-module-size" class="w-8 h-8 rounded-full bg-gray-100 hover:bg-dopamine-sky/20 text-gray-500 hover:text-dopamine-sky flex items-center justify-center transition" title="切换 满宽/半宽并列"><i class="fas fa-expand-arrows-alt"></i></button><div class="drag-handle w-8 h-8 rounded-full bg-gray-100 hover:bg-orange-100 text-gray-500 hover:text-dopamine-orange flex items-center justify-center transition cursor-grab" title="拖拽排序"><i class="fas fa-grip-horizontal"></i></div></div>
        <div class="flex items-center justify-between mb-4 pb-2 border-b border-dopamine-yellow/30 mt-2"><div class="flex items-center gap-2"><i class="fas fa-check-circle text-dopamine-purple text-xl"></i><h2 class="text-xl font-bold text-gray-800">起居注</h2></div></div>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          ${renderRoutineCard('morning','早朝','08:00-12:00','fas fa-sun','bg-gradient-to-br from-orange-50 to-amber-50','border-orange-100/50','text-dopamine-orange','bg-dopamine-orange','bg-dopamine-sky','hover:text-dopamine-orange')}
          ${renderRoutineCard('afternoon','午朝','12:00-18:00','fas fa-cloud-sun','bg-gradient-to-br from-sky-50 to-blue-50','border-sky-100/50','text-dopamine-sky','bg-dopamine-sky','bg-dopamine-purple','hover:text-dopamine-sky')}
          ${renderRoutineCard('evening','晚朝','18:00-23:00','fas fa-moon','bg-gradient-to-br from-purple-50 to-pink-50','border-purple-100/50','text-dopamine-purple','bg-dopamine-purple','bg-dopamine-pink','hover:text-dopamine-purple')}
          ${renderRoutineCard('night','修仙','23:00-次日','none','bg-gradient-to-br from-indigo-50 to-slate-50','border-indigo-100/50','text-dopamine-pink','bg-indigo-400','bg-slate-500','hover:text-indigo-500', true)}
        </div>
      </div>

      <div id="module-tasks" class="draggable-module col-span-1 lg:col-span-1 rounded-2xl shadow-colorful p-5 md:p-6 flex flex-col" style="border-right: 4px solid #F9C74F;">
        <div class="module-controls absolute top-3 right-3 flex gap-2 z-10"><button data-action="toggle-module-size" class="w-8 h-8 rounded-full bg-gray-100 hover:bg-dopamine-sky/20 text-gray-500 hover:text-dopamine-sky flex items-center justify-center transition" title="切换 满宽/半宽并列"><i class="fas fa-expand-arrows-alt"></i></button><div class="drag-handle w-8 h-8 rounded-full bg-gray-100 hover:bg-orange-100 text-gray-500 hover:text-dopamine-orange flex items-center justify-center transition cursor-grab" title="拖拽排序"><i class="fas fa-grip-horizontal"></i></div></div>
        <div class="flex items-center justify-between border-b border-dopamine-yellow/30 pb-3 mb-4 mt-2"><div class="flex items-center gap-2"><i class="fas fa-tasks text-dopamine-pink text-xl"></i><h2 class="text-xl font-bold text-gray-800">中书门下</h2><span class="text-xs bg-dopamine-yellow/30 text-dopamine-orange px-2 py-0.5 rounded-full hidden xl:inline-block">未完顺延</span></div><button id="viewTaskHistoryBtn" class="text-dopamine-pink hover:bg-dopamine-pink hover:text-white border border-pink-100 transition text-xs font-semibold bg-pink-50 px-3 py-1.5 rounded-full flex items-center gap-1 ml-auto shadow-sm relative z-0"><i class="fas fa-history"></i> 资治通鉴</button></div>
        <div class="flex gap-3 mb-5 items-stretch"><div class="relative flex-1"><i class="fas fa-pen absolute left-3 top-1/2 -translate-y-1/2 text-dopamine-orange/50 text-sm"></i><input id="taskInput" type="text" placeholder="输入计划名称..." class="w-full pl-9 pr-3 py-2.5 rounded-xl border border-dopamine-yellow/50 bg-amber-50/30 focus:border-dopamine-orange focus:ring-1 transition outline-none"></div><div class="relative flex-shrink-0"><select id="taskInputPriority" class="task-modal-header-priority h-full min-w-[92px]"><option value="high">🔴紧急</option><option value="medium" selected>🟡重要</option><option value="low">🟢日常</option></select><i class="fas fa-chevron-down pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[10px] text-amber-700/70"></i></div><button data-action="add-task" class="bg-dopamine-pink text-white px-4 py-2.5 rounded-xl shadow-sm flex items-center gap-2 transition font-medium"><i class="fas fa-plus"></i></button></div>
        <div class="flex-1 overflow-y-auto pr-1 min-h-[200px]"><div id="taskList" class="space-y-3"></div><div id="emptyTaskHint" class="text-center text-gray-400 text-sm py-6 hidden flex-col items-center gap-1"><i class="fas fa-clipboard-list text-3xl opacity-40"></i><span>✨ 暂无奏折</span></div></div>
      </div>

      <div id="module-ideas" class="draggable-module col-span-1 lg:col-span-1 rounded-2xl shadow-colorful p-5 md:p-6 flex flex-col" style="border-bottom: 4px solid #43AA8B;">
        <div class="module-controls absolute top-3 right-3 flex gap-2 z-10"><button data-action="toggle-module-size" class="w-8 h-8 rounded-full bg-gray-100 hover:bg-dopamine-sky/20 text-gray-500 hover:text-dopamine-sky flex items-center justify-center transition" title="切换 满宽/半宽并列"><i class="fas fa-expand-arrows-alt"></i></button><div class="drag-handle w-8 h-8 rounded-full bg-gray-100 hover:bg-orange-100 text-gray-500 hover:text-dopamine-orange flex items-center justify-center transition cursor-grab" title="拖拽排序"><i class="fas fa-grip-horizontal"></i></div></div>
        <div class="flex items-center justify-between border-b border-dopamine-mint/30 pb-3 mb-4 mt-2"><div class="flex items-center gap-2"><i class="fas fa-lightbulb text-dopamine-yellow text-xl drop-shadow-md"></i><h2 class="text-xl font-bold text-gray-800">案头拾遗</h2><span class="text-xs bg-dopamine-lime/20 text-dopamine-mint px-2 py-0.5 rounded-full hidden xl:inline-block">捕捉火花</span></div><button id="viewIdeaHistoryBtn" class="text-dopamine-mint hover:bg-dopamine-mint hover:text-white border border-green-100 transition text-xs font-semibold bg-green-50 px-3 py-1.5 rounded-full flex items-center gap-1 ml-auto shadow-sm relative z-0"><i class="fas fa-history"></i> 资治通鉴</button></div>
        <div class="flex gap-2 mb-5 items-stretch"><div class="relative flex-1"><textarea id="ideaInput" rows="2" placeholder="记录瞬间的想法..." class="w-full h-full p-3 rounded-xl border border-dopamine-mint/40 bg-green-50/20 focus:border-dopamine-mint focus:ring-1 transition outline-none resize-none"></textarea></div><button data-action="add-idea" class="bg-dopamine-mint hover:bg-dopamine-mint/80 text-white px-4 sm:px-6 rounded-xl shadow-sm flex flex-col sm:flex-row items-center justify-center gap-1 sm:gap-2 transition flex-shrink-0"><i class="fas fa-bolt text-lg"></i><span class="text-sm font-bold"></span></button></div>
        <div class="flex-1 overflow-y-auto pr-1 min-h-[150px]"><ul id="ideaList" class="space-y-3"></ul><div id="emptyIdeaHint" class="text-center text-gray-400 text-sm py-6 hidden flex-col items-center gap-1"><i class="far fa-comment-dots text-3xl opacity-40"></i><span>随时记录奇思妙想～</span></div></div>
      </div>

      <div id="module-calendar" class="draggable-module col-span-1 lg:col-span-2 rounded-2xl shadow-colorful p-5 md:p-6" style="border-top: 4px solid #4D9DE0;">
        <div class="module-controls absolute top-3 right-3 flex gap-2 z-10"><button data-action="toggle-module-size" class="w-8 h-8 rounded-full bg-gray-100 hover:bg-dopamine-sky/20 text-gray-500 hover:text-dopamine-sky flex items-center justify-center transition" title="切换 满宽/半宽并列"><i class="fas fa-expand-arrows-alt"></i></button><div class="drag-handle w-8 h-8 rounded-full bg-gray-100 hover:bg-orange-100 text-gray-500 hover:text-dopamine-orange flex items-center justify-center transition cursor-grab" title="拖拽排序"><i class="fas fa-grip-horizontal"></i></div></div>
        <div class="flex items-center justify-between border-b border-dopamine-sky/30 pb-3 mb-4 mt-2"><div class="flex items-center gap-2"><i class="fas fa-map-marked-alt text-dopamine-sky text-xl"></i><h2 class="text-xl font-bold text-gray-800">春秋</h2><span class="text-xs bg-dopamine-sky/20 text-dopamine-sky px-2 py-0.5 rounded-full">热力日历</span></div><div class="flex items-center gap-3 ml-auto relative z-0"><button id="prevMonthBtn" class="text-gray-400 hover:text-dopamine-sky transition p-1"><i class="fas fa-chevron-left"></i></button><span id="calendarMonthYear" class="font-bold text-gray-700 text-sm w-20 text-center">202X年X月</span><button id="nextMonthBtn" class="text-gray-400 hover:text-dopamine-sky transition p-1"><i class="fas fa-chevron-right"></i></button></div></div>
        <div class="grid grid-cols-7 gap-1 md:gap-2 text-center text-xs font-bold text-gray-400 mb-2"><div>日</div><div>一</div><div>二</div><div>三</div><div>四</div><div>五</div><div>六</div></div><div id="calendarGrid" class="grid grid-cols-7 gap-1 md:gap-2"></div>
        <div class="mt-6 border-t border-dopamine-sky/20 pt-5"><div class="flex flex-wrap items-center justify-between gap-3 mb-4"><div class="flex items-center gap-2"><i class="fas fa-seedling text-dopamine-mint text-lg"></i><h3 class="text-lg font-bold text-gray-800">日课</h3><span class="text-xs bg-green-50 text-dopamine-mint px-2 py-0.5 rounded-full border border-green-100">次日自动刷新</span></div><div class="flex items-center gap-2"><button data-action="open-habit-modal" class="bg-dopamine-mint text-white px-3 py-1.5 rounded-full text-xs font-semibold shadow-sm hover:opacity-90 transition flex items-center gap-1"><i class="fas fa-plus"></i> 新增日课</button></div></div><div id="habitList" class="space-y-3"></div><div id="emptyHabitHint" class="text-center text-gray-400 text-sm py-6 hidden flex-col items-center gap-1"><i class="fas fa-seedling text-3xl opacity-40"></i><span>还没有打卡习惯，先加一个吧</span></div></div>
      </div>


      <div id="module-food" class="draggable-module col-span-1 lg:col-span-2 rounded-2xl shadow-colorful p-5 md:p-6" style="border-top: 4px solid #A7C957;">
        <div class="module-controls absolute top-3 right-3 flex gap-2 z-10"><button data-action="toggle-module-size" class="w-8 h-8 rounded-full bg-gray-100 hover:bg-dopamine-sky/20 text-gray-500 hover:text-dopamine-sky flex items-center justify-center transition" title="切换 满宽/半宽并列"><i class="fas fa-expand-arrows-alt"></i></button><div class="drag-handle w-8 h-8 rounded-full bg-gray-100 hover:bg-orange-100 text-gray-500 hover:text-dopamine-orange flex items-center justify-center transition cursor-grab" title="拖拽排序"><i class="fas fa-grip-horizontal"></i></div></div>
        <div class="flex flex-wrap items-start justify-between gap-4 border-b border-lime-200/60 pb-3 mb-4 mt-2"><div class="flex items-center gap-2"><i class="fas fa-mug-hot text-dopamine-mint text-xl"></i><div><h2 class="text-xl font-bold text-gray-800">御膳房</h2><p class="text-xs text-gray-500 mt-0.5">今日饮馔与饮子簿</p></div></div><div class="flex items-center gap-2 ml-auto"><button data-action="open-food-record-modal" class="bg-dopamine-mint text-white px-3 py-1.5 rounded-full text-xs font-semibold shadow-sm hover:opacity-90 transition flex items-center gap-1"><i class="fas fa-plus"></i> 新增饮馔</button><button data-action="open-ingredient-modal" class="bg-white text-dopamine-orange px-3 py-1.5 rounded-full text-xs font-semibold border border-dopamine-yellow/50 shadow-sm hover:bg-amber-50 transition flex items-center gap-1"><i class="fas fa-book"></i> 饮子簿</button></div></div>
        <div class="grid grid-cols-1 xl:grid-cols-[minmax(0,1.4fr)_320px] gap-4">
          <div class="min-w-0">
            <div class="grid grid-cols-3 gap-3 mb-4"><div class="food-stat-card"><div class="food-stat-label">今日记录</div><div id="foodSummaryTotal" class="food-stat-value">0</div></div><div class="food-stat-card"><div class="food-stat-label">饮子</div><div id="foodSummaryDrink" class="food-stat-value">0</div></div><div class="food-stat-card"><div class="food-stat-label">已关联饮子</div><div id="foodSummaryLinked" class="food-stat-value">0</div></div></div>
            <div class="food-table-wrap"><table class="w-full text-left min-w-[700px]"><thead><tr class="text-xs text-gray-500"><th class="px-3 py-2 font-bold">时间</th><th class="px-3 py-2 font-bold">类别</th><th class="px-3 py-2 font-bold">名称</th><th class="px-3 py-2 font-bold">数量</th><th class="px-3 py-2 font-bold">饮子簿</th><th class="px-3 py-2 font-bold">备注</th><th class="px-3 py-2 font-bold">操作</th></tr></thead><tbody id="foodTableBody"></tbody></table></div>
            <div id="emptyFoodHint" class="text-center text-gray-400 text-sm py-6 hidden flex-col items-center gap-1"><i class="fas fa-bowl-food text-3xl opacity-40"></i><span>今日还没有饮馔记录</span></div>
          </div>
          <div class="min-w-0 rounded-2xl border border-green-100 bg-gradient-to-b from-green-50/70 to-white p-4 shadow-sm"><div class="flex items-center justify-between gap-2 mb-3"><div><h3 class="font-bold text-gray-800">饮子簿</h3><p class="text-xs text-gray-500 mt-1">茶 / 咖啡 / 花草 / 其他</p></div><button type="button" data-action="open-ingredient-modal" class="text-xs px-3 py-1.5 rounded-full bg-green-100 text-dopamine-mint border border-green-200 font-semibold">+ 新增</button></div><div id="ingredientList" class="space-y-2 max-h-[360px] overflow-y-auto pr-1"></div></div>
        </div>
      </div>


      <div id="module-stats" class="draggable-module col-span-1 lg:col-span-2 rounded-2xl shadow-colorful p-5 md:p-6 flex flex-col" style="background: linear-gradient(135deg, #FFF9F0, #FFF5E6);">
        <div class="module-controls absolute top-3 right-3 flex gap-2 z-10"><button data-action="toggle-module-size" class="w-8 h-8 rounded-full bg-gray-100 hover:bg-dopamine-sky/20 text-gray-500 hover:text-dopamine-sky flex items-center justify-center transition" title="切换 满宽/半宽并列"><i class="fas fa-expand-arrows-alt"></i></button><div class="drag-handle w-8 h-8 rounded-full bg-gray-100 hover:bg-orange-100 text-gray-500 hover:text-dopamine-orange flex items-center justify-center transition cursor-grab" title="拖拽排序"><i class="fas fa-grip-horizontal"></i></div></div>
        <div class="flex items-center gap-2 border-b border-dopamine-yellow/40 pb-3 mb-5 mt-2"><i class="fas fa-chart-pie text-dopamine-purple text-xl"></i><h2 class="text-xl font-bold text-gray-800">簿书</h2><span class="text-xs bg-dopamine-lime/30 text-dopamine-mint px-2 py-0.5 rounded-full">汇总</span></div>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6"><div class="bg-gradient-to-br from-dopamine-orange/10 to-dopamine-yellow/10 rounded-xl p-4 shadow-sm"><div class="flex items-center gap-2 text-dopamine-orange mb-3"><i class="fas fa-calendar-week"></i><h3 class="font-bold text-lg">本周</h3></div><div class="space-y-2 text-sm"><div class="flex justify-between"><span>✅ 批阅奏折:</span><span id="weekTasks" class="font-bold text-dopamine-orange">0</span></div><div class="flex justify-between"><span>⏱️ 理政时长:</span><span id="weekFocus" class="font-bold text-dopamine-orange">0 min</span></div><div class="flex justify-between"><span>📅 上朝天数:</span><span id="weekCheckDays" class="font-bold text-dopamine-orange">0 天</span></div></div></div><div class="bg-gradient-to-br from-dopamine-mint/10 to-dopamine-sky/10 rounded-xl p-4 shadow-sm"><div class="flex items-center gap-2 text-dopamine-mint mb-3"><i class="fas fa-calendar-alt"></i><h3 class="font-bold text-lg">本月</h3></div><div class="space-y-2 text-sm"><div class="flex justify-between"><span>✅ 批阅奏折:</span><span id="monthTasks" class="font-bold text-dopamine-mint">0</span></div><div class="flex justify-between"><span>⏱️ 理政时长:</span><span id="monthFocus" class="font-bold text-dopamine-mint">0 min</span></div><div class="flex justify-between"><span>📅 上朝天数:</span><span id="monthCheckDays" class="font-bold text-dopamine-mint">0 天</span></div></div></div><div class="bg-gradient-to-br from-dopamine-pink/10 to-dopamine-purple/10 rounded-xl p-4 shadow-sm"><div class="flex items-center gap-2 text-dopamine-purple mb-3"><i class="fas fa-chart-line"></i><h3 class="font-bold text-lg">本年</h3></div><div class="space-y-2 text-sm"><div class="flex justify-between"><span>✅ 批阅奏折:</span><span id="yearTasks" class="font-bold text-dopamine-purple">0</span></div><div class="flex justify-between"><span>⏱️ 理政时长:</span><span id="yearFocus" class="font-bold text-dopamine-purple">0 min</span></div><div class="flex justify-between"><span>📅 上朝天数:</span><span id="yearCheckDays" class="font-bold text-dopamine-purple">0 天</span></div></div></div></div>
        <div class="mt-6 border-t border-dopamine-yellow/20 pt-5 w-full"><h3 class="text-sm font-bold text-gray-600 mb-3 flex items-center gap-2"><i class="fas fa-chart-area text-dopamine-sky"></i> 近7天理政趋势</h3><div class="relative h-56 w-full"><canvas id="trendChart"></canvas></div></div>
      </div>
    </div>
  `;
}

function renderRoutineCard(period,title,time,icon,boxBg,border,color,startBg,endBg,editHover,isNight=false){
  return `
    <div class="${boxBg} rounded-xl p-3 shadow-sm border ${border}">
      <div class="flex items-center justify-between mb-2">
        <h3 class="font-bold ${color} text-sm flex items-center gap-1">${isNight ? '🧘‍♂️' : `<i class="${icon}"></i>`} ${title}</h3>
        <span class="text-[10px] ${color}/70">${time}</span>
      </div>
      <div class="flex gap-1.5 mb-2">
        <button data-action="check-time" data-period="${period}" data-type="start" class="flex-1 ${startBg} text-white py-1 rounded text-xs font-bold shadow-sm hover:opacity-80 transition">上朝</button>
        <button data-action="check-time" data-period="${period}" data-type="end" class="flex-1 ${endBg} text-white py-1 rounded text-xs font-bold shadow-sm hover:opacity-80 transition">退朝</button>
        <button data-action="open-check-modal" data-period="${period}" class="bg-white text-gray-400 px-2 py-1 rounded text-xs shadow-sm border border-gray-100 ${editHover} transition" title="补录/复盘"><i class="fas fa-edit"></i></button>
      </div>
      <div id="${period}" class="text-[11px] bg-white rounded p-1.5 text-gray-600 font-mono border min-h-[44px]">始: -  终: -</div>
    </div>
  `;
}
