import { App } from '../core/app-context.js';
import { getTodayStr, escapeHtml } from '../core/utils.js';
import { saveData } from '../core/storage.js';

export function getTodayHabitRecords() { const today = getTodayStr(); if (!App.data.habitRecords[today] || typeof App.data.habitRecords[today] !== 'object') App.data.habitRecords[today] = {}; return App.data.habitRecords[today]; }
export function ensureHabitRecordsForToday() { const todayRecords = getTodayHabitRecords(); let changed = false; App.data.habitDefs.forEach((habit) => { if (!todayRecords[habit.id] || typeof todayRecords[habit.id] !== 'object') { todayRecords[habit.id] = { value: 0, checked: false, updatedAt: 0 }; changed = true; } else { todayRecords[habit.id].value = Number.isFinite(Number(todayRecords[habit.id].value)) ? Number(todayRecords[habit.id].value) : 0; todayRecords[habit.id].checked = !!todayRecords[habit.id].checked; } }); return changed; }
export function hydrateHabitDays() { if (ensureHabitRecordsForToday()) saveData(); }
export function getHabitById(id) { return App.data.habitDefs.find((h) => String(h.id) === String(id)); }
export function getHabitRecordForDate(habitId, dateStr = getTodayStr()) { const dayRecords = App.data.habitRecords[dateStr] || {}; return dayRecords[habitId] || { value: 0, checked: false, updatedAt: 0 }; }
export function setHabitRecord(habitId, patch, dateStr = getTodayStr()) { if (!App.data.habitRecords[dateStr] || typeof App.data.habitRecords[dateStr] !== 'object') App.data.habitRecords[dateStr] = {}; const current = App.data.habitRecords[dateStr][habitId] || { value: 0, checked: false, updatedAt: 0 }; App.data.habitRecords[dateStr][habitId] = { value: patch.value == null || patch.value === '' || !Number.isFinite(Number(patch.value)) ? Number(current.value || 0) : Number(patch.value), checked: typeof patch.checked === 'boolean' ? patch.checked : !!current.checked, updatedAt: Date.now() }; }
export function getHabitProgress(habit, record) { if (!habit?.targetValue || habit.targetValue <= 0) return record.checked ? 100 : 0; return Math.max(0, Math.min(100, (Number(record.value || 0) / Number(habit.targetValue)) * 100)); }
export function openHabitModal(id = '') { const habit = id ? getHabitById(id) : null; document.getElementById('habitModalId').value = habit?.id || ''; document.getElementById('habitModalTitle').innerText = habit ? '编辑打卡习惯' : '新增打卡习惯'; document.getElementById('habitModalName').value = habit?.name || ''; document.getElementById('habitModalUnit').value = habit?.unit || ''; document.getElementById('habitModalTarget').value = habit?.targetValue ?? ''; document.getElementById('habitModalDeleteBtn').classList.toggle('hidden', !habit); document.getElementById('habitModal').classList.add('active'); }
export function closeHabitModal() { document.getElementById('habitModal').classList.remove('active'); }
export function saveHabitFromModal() { const id = document.getElementById('habitModalId').value; const name = document.getElementById('habitModalName').value.trim(); let unit = document.getElementById('habitModalUnit').value.trim(); const rawTarget = document.getElementById('habitModalTarget').value.trim(); const targetValue = rawTarget === '' ? null : Number(rawTarget); if (unit && /^-?\d+(\.\d+)?$/.test(unit)) unit = ''; if (!name) { alert('习惯名称不能为空。'); return; } if (rawTarget !== '' && (!Number.isFinite(targetValue) || targetValue < 0 || !Number.isInteger(targetValue))) { alert('目标量需要是大于等于 0 的整数。'); return; } if (id) { const habit = getHabitById(id); if (!habit) return; habit.name = name; habit.unit = unit; habit.targetValue = targetValue; } else { const newHabitId = `habit_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`; App.data.habitDefs.push({ id: newHabitId, name, unit, targetValue }); ensureHabitRecordsForToday(); } saveData(); renderHabits(); App.api.updateStatistics(); closeHabitModal(); }
export function deleteHabitFromModal() { const id = document.getElementById('habitModalId').value; const habit = getHabitById(id); if (!habit) return; if (!confirm(`确定删除习惯“${habit.name}”吗？历史记录会保留，但今天起不再显示。`)) return; App.data.habitDefs = App.data.habitDefs.filter((h) => String(h.id) !== String(id)); saveData(); renderHabits(); closeHabitModal(); }
export function openHabitRecordModal(habitId) { const habit = getHabitById(habitId); if (!habit) return; const record = getHabitRecordForDate(habit.id); document.getElementById('habitRecordModalId').value = habit.id; document.getElementById('habitRecordModalName').innerText = habit.name; document.getElementById('habitRecordModalUnit').innerText = habit.unit || ''; document.getElementById('habitRecordModalValue').value = Number(record.value || 0); document.getElementById('habitRecordModalChecked').checked = !!record.checked; document.getElementById('habitRecordModal').classList.add('active'); }
export function closeHabitRecordModal() { document.getElementById('habitRecordModal').classList.remove('active'); }
export function saveHabitRecordFromModal() { const habitId = document.getElementById('habitRecordModalId').value; const rawValue = document.getElementById('habitRecordModalValue').value.trim(); const checked = document.getElementById('habitRecordModalChecked').checked; const value = rawValue === '' ? 0 : Number(rawValue); if (!Number.isFinite(value) || value < 0 || !Number.isInteger(value)) { alert('当前数量需要是大于等于 0 的整数。'); return; } setHabitRecord(habitId, { value, checked }); saveData(); renderHabits(); closeHabitRecordModal(); }
export function updateHabitValueInline(habitId, rawValue) { const habit = getHabitById(habitId); if (!habit) return; const value = rawValue === '' ? 0 : Number(rawValue); if (!Number.isFinite(value) || value < 0 || !Number.isInteger(value)) return; const record = getHabitRecordForDate(habitId); let checked = !!record.checked; if (habit.targetValue && habit.targetValue > 0) checked = value >= habit.targetValue ? true : checked; setHabitRecord(habitId, { value, checked }); saveData(); renderHabits(); }
export function toggleHabitChecked(habitId) { const habit = getHabitById(habitId); if (!habit) return; const record = getHabitRecordForDate(habitId); const nextChecked = !record.checked; let nextValue = Number(record.value || 0); if (!habit.targetValue && !habit.unit && nextChecked && nextValue <= 0) nextValue = 1; setHabitRecord(habitId, { value: nextValue, checked: nextChecked }); saveData(); renderHabits(); }
export function quickHabitPunch(habitId) { const habit = getHabitById(habitId); if (!habit) return; const record = getHabitRecordForDate(habitId); let nextValue = Number(record.value || 0); let nextChecked = !!record.checked; if (!habit.unit && !habit.targetValue) { nextChecked = !record.checked; nextValue = nextChecked ? 1 : 0; } else { nextValue += 1; if (habit.targetValue && habit.targetValue > 0 && nextValue >= habit.targetValue) nextChecked = true; } setHabitRecord(habitId, { value: nextValue, checked: nextChecked }); saveData(); renderHabits(); }
export function renderHabits() { hydrateHabitDays(); const list = document.getElementById('habitList'); const empty = document.getElementById('emptyHabitHint'); const habits = [...App.data.habitDefs]; if (!habits.length) { list.innerHTML = ''; empty.classList.remove('hidden'); return; } empty.classList.add('hidden'); list.innerHTML = habits.map((habit) => { const record = getHabitRecordForDate(habit.id); const progress = getHabitProgress(habit, record); const hasValueField = !!habit.unit || !!habit.targetValue; const currentValue = Number(record.value || 0); const statusText = habit.targetValue ? `${Math.round(progress)}%` : (record.checked ? '议定' : '未完成'); return `<div class="habit-row-card"><div class="habit-row-bg"></div><div class="habit-row-fill" style="width:${progress}%;"></div><div class="habit-row-inner"><div class="flex flex-wrap items-center gap-2 md:gap-3 justify-between"><div class="min-w-0 flex items-center gap-2 md:gap-3 flex-wrap"><h4 class="text-sm font-bold text-gray-800">${escapeHtml(habit.name)}</h4>${statusText ? `<span class="text-xs font-semibold text-gray-600">${statusText}</span>` : ''}</div><div class="flex items-center gap-2 flex-wrap justify-end">${hasValueField ? `<span class="habit-inline-value-wrap"><input type="number" min="0" step="1" inputmode="numeric" class="habit-inline-value ${habit.targetValue ? 'targeted' : ''}" value="${currentValue}" data-action="habit-inline-value" data-habit-id="${habit.id}" >${habit.targetValue ? `<span class="text-sm font-semibold text-gray-600">/ ${habit.targetValue}</span>` : ''}</span>${habit.unit ? `<span class="text-[11px] px-2 py-1 rounded-full bg-green-50/90 text-dopamine-mint border border-green-100">${escapeHtml(habit.unit)}</span>` : ''}<button class="habit-action-mini" data-action="quick-habit-punch" data-habit-id="${habit.id}">+1</button>` : `<button class="habit-action-mini ${record.checked ? '!bg-green-50 !text-dopamine-mint !border-green-100' : ''}" data-action="quick-habit-punch" data-habit-id="${habit.id}">${record.checked ? '再记一次' : '+1'}</button>`}<label class="habit-check-chip ${record.checked ? '!bg-green-50 !border-green-100 !text-dopamine-mint' : ''}"><input type="checkbox" ${record.checked ? 'checked' : ''} data-action="toggle-habit-checked" data-habit-id="${habit.id}"><span>完成</span></label><button class="habit-action-mini" data-action="open-habit-record-modal" data-habit-id="${habit.id}" title="编辑记录"><i class="fas fa-pen text-[11px]"></i></button><button class="habit-action-mini" data-action="open-habit-modal" data-habit-id="${habit.id}" title="习惯设置"><i class="fas fa-seedling text-[11px]"></i></button></div></div></div></div>`; }).join(''); }
export function renderHabitRecordsForDate(dateStr) { const dayRecords = App.data.habitRecords?.[dateStr] || {}; const habitIds = Object.keys(dayRecords); if (!habitIds.length) return '<div class="text-xs text-gray-400">无</div>'; return habitIds.map((habitId) => { const record = dayRecords[habitId] || { value: 0, checked: false }; const habit = getHabitById(habitId) || { name: `已删除习惯 (${habitId})`, unit: '', targetValue: null }; const value = Number(record.value || 0); const valueText = habit.targetValue ? `${value}/${habit.targetValue}${habit.unit ? ` ${escapeHtml(habit.unit)}` : ''}` : (habit.unit ? `${value} ${escapeHtml(habit.unit)}` : (record.checked ? '已打卡' : '未打卡')); return `<div class="bg-emerald-50/70 p-2 rounded-xl border border-emerald-100 flex items-center justify-between gap-3"><div class="min-w-0"><div class="font-medium text-gray-800 truncate">${escapeHtml(habit.name)}</div><div class="text-xs text-gray-500 mt-0.5">${valueText}</div></div><span class="text-base flex-shrink-0">${record.checked ? '✅' : '▫️'}</span></div>`; }).join(''); }
export function showHabitHistory() { const container = document.getElementById('habitHistoryList'); const entries = Object.keys(App.data.habitRecords || {}).sort((a, b) => b.localeCompare(a)); container.innerHTML = entries.length ? entries.map((dateStr) => { const dayRecords = App.data.habitRecords[dateStr] || {}; const rows = Object.keys(dayRecords).map((habitId) => { const record = dayRecords[habitId]; const habit = getHabitById(habitId) || { name: `已删除习惯 (${habitId})`, unit: '', targetValue: null }; const valueText = habit.targetValue ? `${Number(record.value || 0)}${habit.unit || ''} / ${habit.targetValue}${habit.unit || ''}` : (habit.unit ? `${Number(record.value || 0)}${habit.unit}` : (record.checked ? '已打卡' : '未打卡')); return `<div class="flex items-center justify-between gap-3 text-sm bg-gray-50 rounded-xl px-3 py-2"><div class="min-w-0"><div class="font-medium text-gray-800">${escapeHtml(habit.name)}</div><div class="text-xs text-gray-500 mt-0.5">${escapeHtml(valueText)}</div></div><span class="text-lg">${record.checked ? '✅' : '▫️'}</span></div>`; }).join(''); if (!rows) return ''; return `<div class="rounded-2xl border border-sky-100 bg-gradient-to-r from-sky-50 to-white p-3"><div class="font-bold text-dopamine-sky mb-2">${dateStr}</div><div class="space-y-2">${rows}</div></div>`; }).filter(Boolean).join('') : '<div class="text-center text-gray-400 py-4"><i class="fas fa-book"></i> 暂无打卡归档</div>'; document.getElementById('habitHistoryModal').classList.add('active'); }
