import { App } from '../core/app-context.js';
import { escapeHtml, formatDateToYMD } from '../core/utils.js';
import { saveData } from '../core/storage.js';

export function getTaskById(id) { return App.data.tasks.find((t) => String(t.id) === String(id)); }
export function renderMarkdown(md) { return !md ? '<div class="text-xs text-gray-400">暂无内容</div>' : marked.parse(md); }
export function setTaskMarkdownEditorVisible(visible) { App.state.taskMarkdownEditorVisible = !!visible; const editorWrap = document.getElementById('taskMarkdownEditorWrap'); const toggleBtn = document.getElementById('taskMarkdownToggleBtn'); if (App.state.taskMarkdownEditorVisible) { editorWrap.classList.remove('hidden'); toggleBtn.innerText = '收起源码'; } else { editorWrap.classList.add('hidden'); toggleBtn.innerText = '编辑 Markdown'; } }
export function toggleTaskMarkdownEditor() { setTaskMarkdownEditorVisible(!App.state.taskMarkdownEditorVisible); }
export function updateTaskMarkdownPreview() { const note = document.getElementById('taskModalNoteMarkdown').value; document.getElementById('taskModalNotePreview').innerHTML = renderMarkdown(note); }
export function getCleanTagList(tags = []) { return [...new Set((Array.isArray(tags) ? tags : []).map((tag) => typeof tag === 'string' ? tag.trim() : '').filter(Boolean))]; }
export function ensureTagPool(tags = []) { const cleanTags = getCleanTagList(tags); let changed = false; cleanTags.forEach((tag) => { if (!App.data.tagPool.includes(tag)) { App.data.tagPool.push(tag); changed = true; } }); if (changed) App.data.tagPool = getCleanTagList(App.data.tagPool); return changed; }
export function getSelectedTagsFromModal() { return getCleanTagList((document.getElementById('taskModalTags')?.dataset.selectedTags || '').split('||')); }
export function setSelectedTagsToModal(tags = []) { const container = document.getElementById('taskModalTags'); if (container) container.dataset.selectedTags = getCleanTagList(tags).join('||'); }
export function renderTagChip(tag, selected = false) { return `<button type="button" class="task-tag-chip inline-flex items-center gap-1 px-3 py-1.5 rounded-full text-xs border transition ${selected ? 'bg-dopamine-purple text-white border-dopamine-purple shadow-sm' : 'bg-white text-gray-600 border-gray-200 hover:border-dopamine-purple/40 hover:text-dopamine-purple'}" data-tag="${escapeHtml(tag)}" data-selected="${selected ? 'true' : 'false'}" title="左键选择，右键删除公共标签"><span>${escapeHtml(tag)}</span>${selected ? '<span class="text-[10px] opacity-90"><i class="fas fa-times"></i></span>' : ''}</button>`; }
export function renderTagsToModal(selectedTags = []) { const container = document.getElementById('taskModalTags'); if (!container) return; const cleanSelected = getCleanTagList(selectedTags); setSelectedTagsToModal(cleanSelected); const pool = getCleanTagList(App.data.tagPool); container.innerHTML = pool.length ? pool.map((tag) => renderTagChip(tag, cleanSelected.includes(tag))).join('') : '<div class="text-xs text-gray-400">暂无公共标签，先在下方添加一个吧</div>'; }
export function collectTagsFromModal() { return getSelectedTagsFromModal(); }
export function toggleTagSelection(tag) { const cleanTag = (tag || '').trim(); if (!cleanTag) return; const selected = getSelectedTagsFromModal(); const nextSelected = selected.includes(cleanTag) ? selected.filter((t) => t !== cleanTag) : [...selected, cleanTag]; renderTagsToModal(nextSelected); }
export function deleteTagFromPool(tag) { const cleanTag = (tag || '').trim(); if (!cleanTag) return; if (!confirm(`确定删除公共标签“${cleanTag}”吗？
删除后会从所有任务里一起移除。`)) return; App.data.tagPool = getCleanTagList(App.data.tagPool).filter((t) => t !== cleanTag); App.data.tasks.forEach((task) => { task.tags = getCleanTagList(task.tags).filter((t) => t !== cleanTag); }); saveData(); const currentTaskId = document.getElementById('taskModalId')?.value; const currentTask = currentTaskId ? getTaskById(currentTaskId) : null; renderTagsToModal(currentTask?.tags || []); renderTasks(); }
export function addTagToPool(tag, options = {}) { const cleanTag = (tag || '').trim(); if (!cleanTag) return false; const existed = App.data.tagPool.includes(cleanTag); ensureTagPool([cleanTag]); const selected = getSelectedTagsFromModal(); if (options.select !== false && !selected.includes(cleanTag)) selected.push(cleanTag); renderTagsToModal(selected); return !existed; }
export function addTagFromInput() { const input = document.getElementById('taskTagInput'); const value = input.value.trim(); if (!value) return; let changed = false; value.split(/[,，、;；]/).map((s) => s.trim()).filter(Boolean).forEach((tag) => { if (addTagToPool(tag, { select: true })) changed = true; }); if (changed) saveData(); input.value = ''; }
export function renderSubtaskRow(subtask = { id: Date.now(), text: '', done: false }) { return `<div class="flex items-center gap-2 subtask-row" data-id="${subtask.id}"><input type="checkbox" class="subtask-done w-4 h-4" ${subtask.done ? 'checked' : ''}><input type="text" class="subtask-text flex-1 p-2 border rounded-lg bg-gray-50 outline-none focus:border-dopamine-orange text-sm" value="${escapeHtml(subtask.text)}" placeholder="输入子任务内容"><button type="button" data-action="remove-subtask" class="text-red-400 px-2 py-1"><i class="fas fa-trash"></i></button></div>`; }
export function addSubtaskInput(subtask) { document.getElementById('taskModalSubtasks').insertAdjacentHTML('beforeend', renderSubtaskRow(subtask)); }
export function removeSubtaskInput(btn) { const row = btn.closest('.subtask-row'); if (row) row.remove(); }
export function collectSubtasksFromModal() { return Array.from(document.querySelectorAll('#taskModalSubtasks .subtask-row')).map((row) => ({ text: row.querySelector('.subtask-text').value.trim(), done: row.querySelector('.subtask-done').checked, id: row.getAttribute('data-id') })).filter((st) => st.text); }
export function getTaskStatusMeta(status) { if (status === '议定') return { className: 'task-status-done', icon: '✅' }; if (status === '在议') return { className: 'task-status-doing', icon: '⚡' }; if (status === '搁置') return { className: 'task-status-paused', icon: '⏸️' }; return { className: 'task-status-not-started', icon: '📝' }; }
export function applyTaskModalStatusStyle(status) { const btn = document.getElementById('taskModalStatus'); if (!btn) return; btn.classList.remove('task-status-not-started','task-status-doing','task-status-done','task-status-paused'); const statusMeta = getTaskStatusMeta(status || '待议'); btn.classList.add(statusMeta.className); btn.dataset.status = status || '待议'; btn.innerHTML = `<span class="text-[11px] leading-none">${statusMeta.icon}</span><span>${escapeHtml(status || '待议')}</span>`; }
export function cycleTaskModalStatus() { const order = ['待议','在议','议定','搁置']; const btn = document.getElementById('taskModalStatus'); if (!btn) return; const current = btn.dataset.status || '待议'; const currentIndex = order.indexOf(current); applyTaskModalStatusStyle(order[(currentIndex + 1) % order.length]); }
export function openTaskModal(id) { const t = getTaskById(id); if (!t) return; document.getElementById('taskModalTitle').innerText = '计划详情'; document.getElementById('taskModalId').value = t.id; document.getElementById('taskModalName').value = t.name || ''; document.getElementById('taskModalStartDate').value = t.startDate || ''; document.getElementById('taskModalDueDate').value = t.dueDate || ''; document.getElementById('taskModalPriority').value = t.priority || 'medium'; document.getElementById('taskModalNoteMarkdown').value = t.noteMarkdown || ''; document.getElementById('taskTagInput').value = ''; document.getElementById('taskModalSubtasks').innerHTML = ''; applyTaskModalStatusStyle(t.status || '待议'); (t.subtasks || []).forEach((subtask) => addSubtaskInput(subtask)); ensureTagPool(t.tags || []); renderTagsToModal(t.tags || []); document.getElementById('taskModalDeleteBtn').classList.remove('hidden'); setTaskMarkdownEditorVisible(false); updateTaskMarkdownPreview(); document.getElementById('taskDetailModal').classList.add('active'); }
export function closeTaskModal() { document.getElementById('taskDetailModal').classList.remove('active'); setTaskMarkdownEditorVisible(false); }
export function addTask() { const name = document.getElementById('taskInput').value.trim(); if (!name) return; const priority = document.getElementById('taskInputPriority')?.value || 'medium'; App.data.tasks.push({ id: Date.now(), name, startDate: '', dueDate: '', subtasks: [], status: '待议', priority, tags: [], noteMarkdown: '', createdAt: Date.now(), completedAt: null }); saveData(); document.getElementById('taskInput').value = ''; renderTasks(); App.api.updateStatistics(); }
export function saveTaskFromModal(shouldClose = true) { const id = document.getElementById('taskModalId').value; const name = document.getElementById('taskModalName').value.trim(); const startDate = document.getElementById('taskModalStartDate').value; const dueDate = document.getElementById('taskModalDueDate').value; const status = document.getElementById('taskModalStatus').dataset.status || '待议'; const priority = document.getElementById('taskModalPriority').value; const tags = collectTagsFromModal(); const subtasks = collectSubtasksFromModal(); const noteMarkdown = document.getElementById('taskModalNoteMarkdown').value; if (!name) { alert('计划名称不能为空。'); return; } if (startDate && dueDate && startDate > dueDate) { alert('开始日期不能晚于截止日期。'); return; } const t = getTaskById(id); if (!t) return; Object.assign(t, { name, startDate, dueDate, status, priority, tags, subtasks, noteMarkdown }); ensureTagPool(tags); if (status === '议定' && !t.completedAt) t.completedAt = Date.now(); if (status !== '议定') t.completedAt = null; saveData(); renderTasks(); App.api.updateStatistics(); if (shouldClose) closeTaskModal(); }
export function deleteTaskFromModal() { const id = document.getElementById('taskModalId').value; if (!id) return; if (!confirm('确定删除这个计划吗？')) return; App.data.tasks = App.data.tasks.filter((t) => String(t.id) !== String(id)); saveData(); renderTasks(); App.api.updateStatistics(); closeTaskModal(); }
export function getPriorityMeta(priority) { if (priority === 'high') return { label: '🔴紧急', className: 'bg-red-50 text-red-600 border-red-100', dotClass: 'bg-red-500', dotRingClass: 'ring-red-100' }; if (priority === 'low') return { label: '🟢日常', className: 'bg-green-50 text-green-600 border-green-100', dotClass: 'bg-green-500', dotRingClass: 'ring-green-100' }; return { label: '🟡重要', className: 'bg-amber-50 text-amber-700 border-amber-100', dotClass: 'bg-amber-400', dotRingClass: 'ring-amber-100' }; }
export function getSubtaskProgress(task) { const subtasks = Array.isArray(task.subtasks) ? task.subtasks : []; const total = subtasks.length; const done = subtasks.filter((st) => st.done).length; return `${done}/${total}`; }
export function getVisibleTaskTags(tags = [], maxUnits = 20, maxCount = 4) { const cleanTags = (Array.isArray(tags) ? tags : []).filter(Boolean); const visible = []; let usedUnits = 0; for (const tag of cleanTags) { const tagUnits = String(tag).trim().length + 2; const nextCount = visible.length + 1; if (nextCount > maxCount || (visible.length > 0 && usedUnits + tagUnits > maxUnits)) break; visible.push(tag); usedUnits += tagUnits; } return { visible, hiddenCount: Math.max(0, cleanTags.length - visible.length) }; }
export function cycleTaskStatus(taskId, event) { if (event) { event.stopPropagation(); event.preventDefault(); } const task = getTaskById(taskId); if (!task) return; const order = ['待议','在议','议定','搁置']; const currentIndex = order.indexOf(task.status || '待议'); const nextStatus = order[(currentIndex + 1) % order.length]; task.status = nextStatus; if (nextStatus === '议定') task.completedAt = task.completedAt || Date.now(); else task.completedAt = null; saveData(); renderTasks(); App.api.updateStatistics(); }
export function deleteTask(taskId, event) { if (event) { event.stopPropagation(); event.preventDefault(); } const task = getTaskById(taskId); if (!task) return; if (!confirm(`确定删除“${task.name}”吗？`)) return; App.data.tasks = App.data.tasks.filter((t) => String(t.id) !== String(taskId)); saveData(); renderTasks(); App.api.updateStatistics(); }
export function shouldShowTaskInMainList(task) { if (!task) return false; if (task.status !== '议定') return true; if (!task.completedAt) return true; return formatDateToYMD(task.completedAt) === App.api.getTodayStr(); }
export function renderTasks() {
  const container = document.getElementById('taskList'); const empty = document.getElementById('emptyTaskHint'); const visibleTasks = App.data.tasks.filter(shouldShowTaskInMainList);
  if (!visibleTasks.length) { container.innerHTML = ''; empty.classList.remove('hidden'); return; }
  empty.classList.add('hidden'); container.innerHTML = '';
  const statusColumns = [
    { key: '待议', icon: '📝', title: '待议', sectionClass: 'bg-gradient-to-br from-amber-50 via-orange-50/70 to-white border-amber-200/80', headerClass: 'text-amber-900 bg-amber-200/90 border-amber-300 shadow-sm' },
    { key: '在议', icon: '⚡', title: '在议', sectionClass: 'bg-gradient-to-br from-blue-50 via-sky-50/80 to-white border-blue-200/80', headerClass: 'text-blue-900 bg-blue-200/90 border-blue-300 shadow-sm' },
    { key: '搁置', icon: '⏸️', title: '搁置', sectionClass: 'bg-gradient-to-br from-slate-50 via-gray-50/90 to-white border-slate-200/80', headerClass: 'text-slate-800 bg-slate-200/95 border-slate-300 shadow-sm' },
    { key: '议定', icon: '✅', title: '议定', sectionClass: 'bg-gradient-to-br from-green-50 via-emerald-50/80 to-white border-green-200/80', headerClass: 'text-green-900 bg-green-200/90 border-green-300 shadow-sm' },
  ];
  const priorityOrder = { high: 0, medium: 1, low: 2 };
  statusColumns.forEach((col) => {
    const section = document.createElement('div'); section.className = `min-w-0 rounded-2xl border p-2.5 shadow-sm ${col.sectionClass}`;
    const tasks = visibleTasks.filter((t) => (t.status || '待议') === col.key).sort((a, b) => { const p = (priorityOrder[a.priority] ?? 99) - (priorityOrder[b.priority] ?? 99); if (p !== 0) return p; return (a.createdAt || 0) - (b.createdAt || 0); });
    const cardsHtml = tasks.length ? tasks.map((t) => { const priorityMeta = getPriorityMeta(t.priority); const statusMeta = getTaskStatusMeta(t.status || '待议'); const progressText = getSubtaskProgress(t); const tagDisplay = getVisibleTaskTags(t.tags || []); return `<div class="bg-gradient-to-r from-amber-50/40 to-white p-3 rounded-xl shadow-sm border border-dopamine-yellow/20 cursor-pointer hover-rainbow" data-action="open-task-modal" data-task-id="${t.id}"><div class="min-w-0"><div class="flex items-center gap-2 min-w-0"><span class="w-2.5 h-2.5 rounded-full ${priorityMeta.dotClass} ring-2 ${priorityMeta.dotRingClass} flex-shrink-0" title="${escapeHtml(priorityMeta.label)}"></span><div class="text-sm font-semibold text-gray-800 truncate flex-1">${escapeHtml(t.name)}</div><span class="inline-flex items-center gap-1 px-2 py-1 rounded-full bg-slate-100 text-slate-600 border border-slate-200 text-[11px] font-semibold flex-shrink-0 leading-none"><i class="fas fa-list-check text-[10px]"></i><span>${escapeHtml(progressText)}</span></span><button type="button" class="inline-flex items-center justify-center w-8 h-8 rounded-full border font-semibold leading-none transition flex-shrink-0 ${statusMeta.className}" data-action="cycle-task-status" data-task-id="${t.id}" title="${escapeHtml(t.status || '待议')}"><span class="text-[13px] leading-none">${statusMeta.icon}</span></button><button type="button" class="inline-flex items-center justify-center w-8 h-8 rounded-full border border-red-100 bg-red-50 text-red-400 hover:bg-red-100 hover:text-red-500 transition flex-shrink-0" data-action="delete-task" data-task-id="${t.id}" title="删除任务"><i class="fas fa-trash text-[11px]"></i></button></div><div class="mt-2 flex items-center gap-1 overflow-hidden whitespace-nowrap text-[11px] min-h-[24px]">${tagDisplay.visible.length ? tagDisplay.visible.map((tag) => `<span class="inline-flex items-center px-2 py-1 rounded-full bg-purple-50 text-dopamine-purple border border-purple-100 flex-shrink-0 max-w-[88px] truncate">${escapeHtml(tag)}</span>`).join('') : '<span class="text-gray-300">&nbsp;</span>'}${tagDisplay.hiddenCount > 0 ? `<span class="inline-flex items-center px-2 py-1 rounded-full bg-gray-100 text-gray-500 border border-gray-200 flex-shrink-0">+${tagDisplay.hiddenCount}</span>` : ''}</div></div></div>`; }).join('') : '<div class="text-xs text-gray-400 bg-gray-50/80 border border-dashed border-gray-200 rounded-xl px-3 py-5 text-center">暂无任务</div>';
    section.innerHTML = `<div class="flex items-center justify-between gap-2 mb-2 px-1"><div class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full border text-xs font-extrabold tracking-[0.01em] ${col.headerClass}"><span>${col.icon}</span><span>${col.title}</span></div><span class="text-[11px] font-bold text-gray-500">${tasks.length}</span></div><div class="space-y-2">${cardsHtml}</div>`;
    container.appendChild(section);
  });
}
export function showTaskHistory() { const container = document.getElementById('taskHistoryList'); const completed = App.data.tasks.filter((t) => t.status === '议定' && t.completedAt).sort((a, b) => b.completedAt - a.completedAt); container.innerHTML = completed.length === 0 ? '<div class="text-center text-gray-400 py-4"><i class="fas fa-check-circle"></i> 暂无已批奏折</div>' : completed.map((task) => `<div class="flex justify-between items-center bg-gradient-to-r from-pink-50 to-white p-3 rounded-xl shadow-sm border-l-4 border-dopamine-pink"><div><span class="text-sm font-medium">✅ ${escapeHtml(task.name)}</span><div class="text-xs text-gray-400">完成于 ${formatDateToYMD(task.completedAt)}</div></div></div>`).join(''); document.getElementById('taskHistoryModal').classList.add('active'); }
