export const App = {
  data: { tasks: [], focusSessions: [], checkRecords: {}, ideas: [], moodHistory: {}, tagPool: [], habitDefs: [], habitRecords: {}, ingredientDefs: [], foodRecords: {} },
  state: {
    activeFocusStart: null,
    focusTimerInterval: null,
    remainingSeconds: 0,
    currentFocusMode: 'free',
    currentCalendarDate: new Date(),
    focusTrendChart: null,
    isLayoutLocked: true,
    currentTabId: null,
    focusHeartbeatInterval: null,
    focusStorageListenerBound: false,
    lastUserActivityPersistAt: 0,
    pendingSettlementModalOpen: false,
    taskMarkdownEditorVisible: false,
    lastAppliedAppDataMeta: { updatedAt: 0, sourceTabId: null },
  },
  constants: {
    APP_DATA_KEY: 'phd_pro_v2',
    FOCUS_RUNTIME_KEY: 'phd_focus_runtime_v1',
    FOCUS_TAB_ID_KEY: 'phd_focus_tab_id_v1',
    FOCUS_HEARTBEAT_MS: 2000,
    FOCUS_STALE_MS: 6000,
    FOCUS_INACTIVITY_LIMIT_MS: 8 * 60 * 60 * 1000,
    FOCUS_PENDING_SETTLEMENT_KEY: 'phd_focus_pending_settlement_v1',
    USER_ACTIVITY_WRITE_THROTTLE_MS: 15000,
    LAYOUT_KEY: 'phd_pro_layout_v3',
    AVATAR_KEY: 'phd_pro_avatar',
  },
  api: {},
};
